CREATE TABLE IF NOT EXISTS E(
    EKEY INT PRIMARY KEY,
    BREF INT,
    BREF2 INT
);

CREATE TABLE IF NOT EXISTS D(
    DKEY INT PRIMARY KEY,
    EREF INT,
    FOREIGN KEY (EREF) REFERENCES E
);

CREATE TABLE IF NOT EXISTS C(
    CKEY INT PRIMARY KEY,
    AREF INT
);

CREATE TABLE IF NOT EXISTS B(
    BKEY INT,
    BKEY2 INT,
    CREF INT,
    DREF INT,
    PRIMARY KEY (BKEY, BKEY2),
    FOREIGN KEY (CREF) REFERENCES C,
    FOREIGN KEY (DREF) REFERENCES D

);

CREATE TABLE IF NOT EXISTS A(
    AKEY INT PRIMARY KEY,
    BREF INT,
    BREF2 INT,
    FOREIGN KEY (BREF, BREF2) REFERENCES B(BKEY, BKEY2)
);

ALTER TABLE C ADD FOREIGN KEY (AREF) REFERENCES A(AKEY);
ALTER TABLE E ADD FOREIGN KEY (BREF, BREF2) REFERENCES B(BKEY, BKEY2);