CREATE TABLE IF NOT EXISTS A(
    AKEY INT PRIMARY KEY,
    BKEY INT
);

CREATE TABLE IF NOT EXISTS B(
    BKEY INT PRIMARY KEY,
    BKEY_REF INT,
    CKEY INT,
    DKEY INT
);

CREATE TABLE IF NOT EXISTS C(
    CKEY INT PRIMARY KEY,
    AKEY INT
);

CREATE TABLE IF NOT EXISTS D(
    DKEY INT PRIMARY KEY,
    EKEY INT
);

CREATE TABLE IF NOT EXISTS E(
    EKEY INT PRIMARY KEY,
    BKEY INT
);

CREATE TABLE IF NOT EXISTS F(
    FKEY INT PRIMARY KEY,
    GKEY INT,
    BKEY INT
);

CREATE TABLE IF NOT EXISTS G(
    GKEY INT PRIMARY KEY,
    HKEY INT
);

CREATE TABLE IF NOT EXISTS H(
    HKEY INT PRIMARY KEY,
    FKEY INT
);

CREATE TABLE IF NOT EXISTS I(
    IKEY INT PRIMARY KEY,
    JKEY INT
);

CREATE TABLE IF NOT EXISTS J(
  JKEY INT PRIMARY KEY,
  KKEY INT
);

CREATE TABLE IF NOT EXISTS K(
  KKEY INT PRIMARY KEY,
  IKEY INT
);

ALTER TABLE A ADD FOREIGN KEY (BKEY) REFERENCES B(BKEY);
ALTER TABLE B ADD FOREIGN KEY (BKEY_REF) REFERENCES B(BKEY);
ALTER TABLE B ADD FOREIGN KEY (CKEY) REFERENCES C(CKEY);
ALTER TABLE B ADD FOREIGN KEY (DKEY) REFERENCES D(DKEY);
ALTER TABLE C ADD FOREIGN KEY (AKEY) REFERENCES A(AKEY);
ALTER TABLE D ADD FOREIGN KEY (EKEY) REFERENCES E(EKEY);
ALTER TABLE E ADD FOREIGN KEY (BKEY) REFERENCES B(BKEY);
ALTER TABLE F ADD FOREIGN KEY (GKEY) REFERENCES G(GKEY);
ALTER TABLE F ADD FOREIGN KEY (BKEY) REFERENCES B(BKEY);
ALTER TABLE G ADD FOREIGN KEY (HKEY) REFERENCES H(HKEY);
ALTER TABLE H ADD FOREIGN KEY (FKEY) REFERENCES F(FKEY);
ALTER TABLE I ADD FOREIGN KEY (JKEY) REFERENCES J(JKEY);
ALTER TABLE J ADD FOREIGN KEY (KKEY) REFERENCES K(KKEY);
ALTER TABLE K ADD FOREIGN KEY (IKEY) REFERENCES I(IKEY);