
CREATE TABLE IF NOT EXISTS B(
    BKEY INT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS D(
    DKEY INT PRIMARY KEY,
    BREF INT,
    FOREIGN KEY (BREF) REFERENCES B
);

CREATE TABLE IF NOT EXISTS C(
    CKEY INT PRIMARY KEY,
    DREF INT,
    FOREIGN KEY (DREF) REFERENCES D
);

CREATE TABLE IF NOT EXISTS A(
    AKEY INT PRIMARY KEY,
    BREF INT,
    CREF INT,
    FOREIGN KEY (BREF) REFERENCES B,
    FOREIGN KEY (CREF) REFERENCES C
)