CREATE TABLE IF NOT EXISTS E(
    EKEY INT PRIMARY KEY,
    BREF INT
);

CREATE TABLE IF NOT EXISTS D(
    DKEY INT PRIMARY KEY,
    EREF INT,
    FOREIGN KEY (EREF) REFERENCES E
);

CREATE TABLE IF NOT EXISTS C(
    CKEY INT PRIMARY KEY,
    AREF INT
);

CREATE TABLE IF NOT EXISTS B(
    BKEY INT PRIMARY KEY,
    CREF INT,
    DREF INT,
    FOREIGN KEY (CREF) REFERENCES C,
    FOREIGN KEY (DREF) REFERENCES D

);

CREATE TABLE IF NOT EXISTS A(
    AKEY INT PRIMARY KEY,
    BREF INT,
    FOREIGN KEY (BREF) REFERENCES B
)