CREATE TABLE IF NOT EXISTS TEAM_MEMBERS(
    TEAM_ID INTEGER,
    STUDENT_ID INTEGER
);

ALTER TABLE IF EXISTS USERS ADD FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS;

ALTER TABLE IF EXISTS STUDENTS ADD FOREIGN KEY (TEAM_ID) REFERENCES TEAMS;

ALTER TABLE IF EXISTS TEAMS ADD FOREIGN KEY (LIAISON) REFERENCES STUDENTS;

ALTER TABLE IF EXISTS TEAM_MEMBERS ADD FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS;

ALTER TABLE IF EXISTS TEAM_MEMBERS ADD FOREIGN KEY (TEAM_ID) REFERENCES TEAMS;

