
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID SERIAL PRIMARY KEY,
    STUDENT_ID INTEGER,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS STUDENTS(
    STUDENT_ID INTEGER PRIMARY KEY,
    TEAM_ID INTEGER,
    STUDENT_PROGRAM VARCHAR(255) NOT NULL,
    COURSE_SECTION VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TEAMS(
    TEAM_ID SERIAL PRIMARY KEY,
    TEAM_NAME VARCHAR(255) DEFAULT '',
    LIAISON INTEGER
)

