CREATE TABLE IF NOT EXISTS USERS(
    ID UUID PRIMARY KEY,
    NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR UNIQUE,
    ADDRESS VARCHAR,
    CREATED TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPANIES(
    ID UUID PRIMARY KEY,
    NAME VARCHAR,
    EMAIL VARCHAR UNIQUE,
    CREATED TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS(
    ID UUID PRIMARY KEY,
    COMPANY_ID UUID NOT NULL,
    ITEM_NAME VARCHAR NOT NULL,
    PRICE FLOAT,
    QUANTITY INTEGER,
    DESCRIPTION VARCHAR,
    CREATED TIMESTAMP NOT NULL,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES
);

CREATE TABLE IF NOT EXISTS PURCHASES (
    USER_ID UUID,
    PRODUCT_ID UUID,
    QUANTITY INTEGER,
    CREATED TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS
)