CREATE TABLE IF NOT EXISTS TEMPLATE(
    uuid UUID,
    int INT,
    float FLOAT,
    bool BOOLEAN,
    varchar VARCHAR,
    date DATE
);

CREATE TABLE IF NOT EXISTS IRRELIVANT(
    key SERIAL PRIMARY KEY
)