CREATE TABLE IF NOT EXISTS A(
    AKEY INT,
    FLOAT4 float4,
    FLOAT8 float8,
    NUMERICDEF NUMERIC,
    NUMERIC NUMERIC(2, 5),
    VARCHAR VARCHAR(200),
    BPCHAR bpchar(30),
    CHAR bpchar(1),
    BPCHARDEF bpchar,
    BKEY INT,
    PRIMARY KEY (AKEY, FLOAT4, FLOAT8, NUMERICDEF, NUMERIC, VARCHAR, BPCHAR, CHAR, BPCHARDEF)
);

CREATE TABLE IF NOT EXISTS B(
    BKEY INT PRIMARY KEY,
    AKEY INT,
    FLOAT4 float4,
    FLOAT8 float8,
    NUMERICDEF NUMERIC,
    NUMERIC NUMERIC(2, 5),
    VARCHAR VARCHAR(200),
    BPCHAR bpchar(30),
    CHAR bpchar(1),
    BPCHARDEF bpchar,
    FOREIGN KEY (AKEY, FLOAT4, FLOAT8, NUMERICDEF, NUMERIC, VARCHAR, BPCHAR, CHAR, BPCHARDEF) REFERENCES A(AKEY, FLOAT4, FLOAT8, NUMERICDEF, NUMERIC, VARCHAR, BPCHAR, CHAR, BPCHARDEF)
);

ALTER TABLE A ADD FOREIGN KEY (BKEY) REFERENCES B(BKEY)