/*
Copyright © 2025 NAME HERE <EMAIL ADDRESS>
*/
package update

import (
	"log"

	"github.com/spf13/cobra"
)

var (
	ConnString string
)

// UpdateCmd represents the update command
var UpdateCmd = &cobra.Command{
	Use:   "update",
	Short: "The palette responsible for updating files generated by the CLI.",
	Long: `This palette is responsible for updating files generated by the CLI.
Currently, it only updates template files generated by "dbvg generate template"
`,
	Run: func(cmd *cobra.Command, args []string) {
		cmd.Help()
	},
}

func addSubCommands() {
	UpdateCmd.AddCommand(templateCmd)
}

func init() {
	UpdateCmd.PersistentFlags().StringVarP(&ConnString, "database", "", "", "url to connect to the database with")

	if err := UpdateCmd.MarkPersistentFlagRequired("database"); err != nil {
		log.Fatal(err)
	}
	addSubCommands()

	// Here you will define your flags and configuration settings.

	// Cobra supports Persistent Flags which will work for this command
	// and all subcommands, e.g.:
	// updateCmd.PersistentFlags().String("foo", "", "A help for foo")

	// Cobra supports local flags which will only run when this command
	// is called directly, e.g.:
	// updateCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}
